# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20170316_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=15)),
                ('pass1', models.CharField(max_length=15)),
                ('email1', models.CharField(max_length=20)),
                ('Adhar', models.CharField(default='1234-5678-9012', max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='stock1',
            name='lat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock1',
            name='log',
            field=models.TextField(blank=True),
        ),
    ]
