# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20170316_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock1',
            old_name='lat',
            new_name='lati',
        ),
        migrations.RenameField(
            model_name='stock1',
            old_name='log',
            new_name='long',
        ),
    ]
