# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20170328_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dummy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duser1', models.CharField(max_length=15)),
                ('bf', models.IntegerField(default=0)),
            ],
        ),
    ]
