# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock1',
            name='email1',
            field=models.TextField(blank=True),
        ),
    ]
